### ISSUE TITLE
Implement fractions

### ISSUE THREAD

**Issue by AldenMB** [AldenMB/calculator_emulator#6]
The buttons ab/c, d/c, and F<>D should do their thing.

**Comment by wscott** [comment]
It seems they work now.

**Comment by AldenMB** [comment]
Thanks for pointing this out. When I last worked on this my automated tests revealed some edge cases where the emulator was rounding differently from the physical calculator, and I had to pause work on this before I got those ironed out. I suppose that yak-shaving expedition has gone on long enough. We can call this feature implemented, despite edge case rounding weirdness.
